#!/usr/bin/env python3
"""Public surface audit for the Daniya Summer Pet repository.

Read-only checks. Exit 0 = PASS, Exit 1 = FAIL.
Run: python tools/audit_repo_surface.py
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
FAILED = False


def fail(check_name: str, message: str) -> None:
    global FAILED
    FAILED = True
    print(f"  FAIL [{check_name}]: {message}")


def ok(check_name: str) -> None:
    print(f"  PASS [{check_name}]")


def run_git(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        capture_output=True,
        cwd=REPO_ROOT,
        encoding="utf-8",
        errors="replace",
        text=True,
    )


def git_ls_files(*patterns: str) -> list[str]:
    result = run_git(["ls-files", "--", *patterns])
    return [line for line in result.stdout.splitlines() if line]


def git_grep(pattern: str) -> list[str]:
    result = run_git(["grep", "-nI", pattern, "--"])
    if result.returncode == 1:
        return []
    return [line for line in result.stdout.splitlines() if line]


def tracked_text_files() -> list[str]:
    patterns = ["*.py", "*.bat", "*.yaml", "*.yml", "*.json", "*.md", "*.txt"]
    files: list[str] = []
    for pattern in patterns:
        files.extend(git_ls_files(pattern))
    return sorted(set(files))


def check_1_sensitive_paths() -> None:
    name = "Check 1: Tracked sensitive paths"
    print(f"\n{name}")
    sensitive = [
        ".env",
        "data/",
        "assets/private/",
        "models/",
        "backups/",
        "release/",
        "dist/",
        "build/",
        "config/api_config.json",
        "config/multimodal_config.json",
    ]
    found: list[str] = []
    for pattern in sensitive:
        found.extend(git_ls_files(pattern))
    if found:
        for filepath in sorted(set(found)):
            fail(name, f"Sensitive path tracked: {filepath}")
    else:
        ok(name)


def check_2_ai_agent_traces() -> None:
    name = "Check 2: AI agent traces"
    print(f"\n{name}")
    allowed_codex_paths = {
        "AGENTS.md",
        "docs/CUSTOM_API_PROVIDER_GUIDE.md",
        "src/settings_window.py",
        "tools/audit_repo_surface.py",
    }
    any_fail = False
    for line in git_grep("Codex"):
        filepath = line.split(":", 1)[0]
        if filepath not in allowed_codex_paths:
            fail(name, f"Unexpected Codex reference: {line}")
            any_fail = True

    generated_markers = [
        "Generated by ChatGPT",
        "Generated by Codex",
        "Codex execution",
        "AI audit",
        "Repository Public Surface Cleanup",
    ]
    for marker in generated_markers:
        for line in git_grep(marker):
            filepath = line.split(":", 1)[0]
            if filepath != "tools/audit_repo_surface.py":
                fail(name, f"Generated-content marker found: {line}")
                any_fail = True

    if not any_fail:
        ok(name)


def check_3_docs_process_reports() -> None:
    name = "Check 3: Docs process reports"
    print(f"\n{name}")
    blocked_patterns = [
        re.compile(r"^docs/archive/"),
        re.compile(r"^docs/.*CODEX", re.IGNORECASE),
        re.compile(r"^docs/.*FULL_", re.IGNORECASE),
        re.compile(r"^docs/.*FINAL_", re.IGNORECASE),
        re.compile(r"^docs/.*_AUDIT", re.IGNORECASE),
        re.compile(r"^docs/.*_REPORT", re.IGNORECASE),
        re.compile(r"^docs/.*BUG_FIX_PLAN", re.IGNORECASE),
        re.compile(r"^docs/.*REGRESSION_TEST", re.IGNORECASE),
        re.compile(r"^docs/.*INTEGRATION_LOG", re.IGNORECASE),
        re.compile(r"^docs/.*KNOWN_ISSUES_v", re.IGNORECASE),
        re.compile(r"^docs/.*GITHUB_RELEASE_NOTES_v", re.IGNORECASE),
    ]
    found = []
    for filepath in git_ls_files("docs/"):
        if any(pattern.search(filepath) for pattern in blocked_patterns):
            found.append(filepath)

    if found:
        for filepath in sorted(set(found)):
            fail(name, f"Process/audit document tracked: {filepath}")
    else:
        ok(name)


def check_4_release_package_rules() -> None:
    name = "Check 4: Release package rules"
    print(f"\n{name}")
    pack_bat = REPO_ROOT / "pack.bat"
    if not pack_bat.exists():
        fail(name, "pack.bat not found")
        return

    content = pack_bat.read_text(encoding="utf-8")
    raw_docs_copy = re.search(r'robocopy\s+"docs"', content, re.IGNORECASE)
    if raw_docs_copy:
        fail(name, "pack.bat bulk-copies raw docs/")
    elif 'for %%F in (' not in content or 'copy /Y "docs\\%%F"' not in content:
        fail(name, "pack.bat does not use a per-file docs whitelist")
    else:
        required_docs = [
            "README.md",
            "known_issues.md",
            "release_checklist.md",
            "DESTRUCTIVE_TEST_POLICY.md",
        ]
        missing = [
            doc
            for doc in required_docs
            if not (REPO_ROOT / "docs" / doc).exists() or doc not in content
        ]
        if missing:
            for doc in missing:
                fail(name, f"Required release doc missing from docs whitelist: {doc}")
        else:
            ok(name)


def check_5_docs_readme_links() -> None:
    name = "Check 5: docs/README links"
    print(f"\n{name}")
    docs_readme = REPO_ROOT / "docs" / "README.md"
    if not docs_readme.exists():
        fail(name, "docs/README.md not found")
        return

    content = docs_readme.read_text(encoding="utf-8")
    link_pattern = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    broken: list[str] = []
    for match in link_pattern.finditer(content):
        target = match.group(1)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        if not (docs_readme.parent / target).exists():
            broken.append(target)

    if broken:
        for target in sorted(set(broken)):
            fail(name, f"Broken docs link: {target}")
    else:
        ok(name)


def check_6_hidden_unicode() -> None:
    name = "Check 6: Hidden Unicode characters"
    print(f"\n{name}")
    hidden_chars = re.compile(r"[\u200b-\u200f\u2028-\u202f\u2060-\u206f\ufeff]")
    any_fail = False
    for filepath in tracked_text_files():
        fullpath = REPO_ROOT / filepath
        if not fullpath.exists():
            continue
        try:
            with fullpath.open("r", encoding="utf-8") as handle:
                for lineno, line in enumerate(handle, 1):
                    if hidden_chars.search(line):
                        fail(name, f"Hidden Unicode in {filepath}:{lineno}")
                        any_fail = True
                        break
        except (OSError, UnicodeDecodeError):
            continue
    if not any_fail:
        ok(name)


def check_7_readme_clone_url() -> None:
    name = "Check 7: README clone URL"
    print(f"\n{name}")
    readme = REPO_ROOT / "README.md"
    if not readme.exists():
        fail(name, "README.md not found")
        return
    content = readme.read_text(encoding="utf-8")
    if "<your-username>" in content:
        fail(name, "README.md contains placeholder <your-username>")
    else:
        ok(name)


def check_8_forbidden_tracked_artifacts() -> None:
    name = "Check 8: Tracked generated artifacts"
    print(f"\n{name}")
    blocked = [
        re.compile(r"\.docx$", re.IGNORECASE),
        re.compile(r"\.pdf$", re.IGNORECASE),
        re.compile(r"\.log$", re.IGNORECASE),
        re.compile(r"\.spec$", re.IGNORECASE),
        re.compile(r"^run_verify\.py$"),
        re.compile(r"^nul$"),
        re.compile(r"^\.repo_audit_tracked_files\.txt$"),
    ]
    found = []
    for filepath in git_ls_files():
        if any(pattern.search(filepath) for pattern in blocked):
            found.append(filepath)

    if found:
        for filepath in sorted(set(found)):
            fail(name, f"Generated/local artifact tracked: {filepath}")
    else:
        ok(name)


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print("=" * 60)
    print("Daniya Summer Pet - Public Surface Audit")
    print("=" * 60)

    check_1_sensitive_paths()
    check_2_ai_agent_traces()
    check_3_docs_process_reports()
    check_4_release_package_rules()
    check_5_docs_readme_links()
    check_6_hidden_unicode()
    check_7_readme_clone_url()
    check_8_forbidden_tracked_artifacts()

    print("\n" + "=" * 60)
    if FAILED:
        print("RESULT: FAIL - issues found above")
        sys.exit(1)
    print("RESULT: PASS - all checks clean")


if __name__ == "__main__":
    main()
